version: "3.9"

services:
  # Using host XAMPP MySQL instead of separate MariaDB container
  # This allows Docker to use your existing XAMPP data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_NAME: edsight
      DB_USER: root
      DB_PASSWORD: ""
      SECRET_KEY: ${SECRET_KEY:-change-me}
      DEBUG: ${DEBUG:-False}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-*}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - staticfiles:/vol/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 10s
      timeout: 5s
      retries: 10

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    depends_on:
      django:
        condition: service_started
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_NAME: edsight
      DB_USER: root
      DB_PASSWORD: ""
      DJANGO_HOST: django
      REDIS_URL: redis://redis:6379/0
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  celery:
    build:
      context: .
      dockerfile: Dockerfile.django
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_NAME: edsight
      DB_USER: root
      DB_PASSWORD: ""
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: ["bash", "-lc", "celery -A app worker -l info"]
    volumes:
      - .:/app

  # phpMyAdmin removed - use XAMPP's phpMyAdmin instead
  # Access via: http://localhost/phpmyadmin

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      django:
        condition: service_started
      fastapi:
        condition: service_started
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - staticfiles:/vol/static:ro

volumes:
  staticfiles:

