services:
  # Fully containerized MySQL database
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: edsight_root
      MYSQL_DATABASE: edsight
      MYSQL_USER: edsight
      MYSQL_PASSWORD: edsight_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_updates/edsight.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.docker
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: edsight
      DB_USER: edsight
      DB_PASSWORD: edsight_pass
      SECRET_KEY: ${SECRET_KEY:-change-me-in-production}
      DEBUG: ${DEBUG:-False}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-*}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - staticfiles:/vol/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    depends_on:
      mysql:
        condition: service_healthy
      django:
        condition: service_started
    env_file:
      - .env.docker
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: edsight
      DB_USER: edsight
      DB_PASSWORD: edsight_pass
      DJANGO_HOST: django
      REDIS_URL: redis://redis:6379/0
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: Dockerfile.django
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.docker
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: edsight
      DB_USER: edsight
      DB_PASSWORD: edsight_pass
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: ["bash", "-lc", "celery -A app worker -l info"]
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'
    restart: unless-stopped

  # phpMyAdmin removed - use XAMPP's phpMyAdmin instead
  # Access via: http://localhost/phpmyadmin

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      django:
        condition: service_started
      fastapi:
        condition: service_started
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - staticfiles:/vol/static:ro

volumes:
  staticfiles:
  mysql_data:

