# Generated by Django 4.2.24 on 2025-10-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='can_skip',
            field=models.BooleanField(default=False, help_text='Whether this sub-section can be skipped'),
        ),
        migrations.AddField(
            model_name='topic',
            name='can_skip',
            field=models.BooleanField(default=False, help_text='Whether this topic can be skipped'),
        ),
    ]
