# Generated by Django 4.2.24 on 2025-10-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_subquestion_question_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='answer',
            name='idx_answers_sub_question',
        ),
        migrations.RemoveIndex(
            model_name='topic',
            name='topic_sub_section_id_idx',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='sub_question',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='sub_section',
        ),
    ]
