# Generated by Django 5.2.4 on 2025-01-27 12:05

from django.db import migrations


def final_cleanup(apps, schema_editor):
    """Final cleanup of any remaining legacy tables"""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # Drop any remaining legacy tables
        try:
            cursor.execute("DROP TABLE IF EXISTS sub_questions")
        except Exception:
            pass
        try:
            cursor.execute("DROP TABLE IF EXISTS sub_sections")
        except Exception:
            pass


def reverse_final_cleanup(apps, schema_editor):
    """Reverse operation - not implemented"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_clean_legacy_tables'),
    ]

    operations = [
        migrations.RunPython(final_cleanup, reverse_final_cleanup),
    ]
