# Generated by Django 5.2.4 on 2025-01-27 12:10

from django.db import migrations


def remove_sub_question_from_answers(apps, schema_editor):
    """Remove sub_question_id column from answers table"""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # Drop foreign key constraint first
        try:
            cursor.execute("""
                ALTER TABLE answers 
                DROP FOREIGN KEY answers_sub_question_id_302ddcc6_fk_sub_quest
            """)
        except Exception:
            pass
        
        # Drop the column
        try:
            cursor.execute("ALTER TABLE answers DROP COLUMN sub_question_id")
        except Exception:
            pass


def reverse_remove_sub_question_from_answers(apps, schema_editor):
    """Reverse operation - not implemented"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_final_cleanup'),
    ]

    operations = [
        migrations.RunPython(remove_sub_question_from_answers, reverse_remove_sub_question_from_answers),
    ]
