# Generated by Django 4.2.24 on 2025-10-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_sub_question_from_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('percentage', 'Percentage'), ('choice', 'Choice')], max_length=10),
        ),
    ]
