# Generated by Django 4.2.24 on 2025-11-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_choice_answer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsection',
            name='category',
        ),
        migrations.DeleteModel(
            name='SubQuestion',
        ),
        migrations.DeleteModel(
            name='SubSection',
        ),
    ]
