# Generated by Django 4.2.24 on 2025-11-03 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_fix_form_user_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormRemark',
            fields=[
                ('remark_id', models.AutoField(primary_key=True, serialize=False)),
                ('remark_type', models.CharField(choices=[('category', 'Category'), ('topic', 'Topic'), ('question', 'Question')], help_text='Type of entity this remark is attached to', max_length=10)),
                ('entity_id', models.IntegerField(help_text='ID of the category, topic, or question')),
                ('remark_text', models.TextField(help_text='The remark content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks_made', to='core.adminuser')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='core.form')),
            ],
            options={
                'db_table': 'form_remarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='formremark',
            index=models.Index(fields=['form'], name='idx_form_remarks_form'),
        ),
        migrations.AddIndex(
            model_name='formremark',
            index=models.Index(fields=['remark_type', 'entity_id'], name='idx_form_remarks_type_entity'),
        ),
        migrations.AddIndex(
            model_name='formremark',
            index=models.Index(fields=['admin_user'], name='idx_form_remarks_admin'),
        ),
        migrations.AddIndex(
            model_name='formremark',
            index=models.Index(fields=['created_at'], name='idx_form_remarks_created'),
        ),
    ]
