# Generated by Django 5.2.4 on 2025-07-29 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usersschool_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('sub_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_question_text', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=1)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
            options={
                'db_table': 'sub_questions',
                'indexes': [models.Index(fields=['question'], name='idx_sub_questions_question_id'), models.Index(fields=['display_order'], name='idx_sub_questions_order')],
            },
        ),
    ]
