# Generated by Django 5.2.4 on 2025-08-13 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dataretentionpolicy_encryptionkey_and_more'),
    ]

    operations = [
    ]
