# Generated by Django 5.2.4 on 2025-08-13 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20250813_1240'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS two_factor_auth;",
            reverse_sql="CREATE TABLE two_factor_auth (id INT AUTO_INCREMENT PRIMARY KEY);"
        ),
    ]