# Generated by Django 5.2.4 on 2025-08-14 01:53

from django.db import migrations


def ensure_form_user_consistency(apps, schema_editor):
    """Ensure all forms have proper user assignments and clean up inconsistent data"""
    Form = apps.get_model('app', 'Form')
    UsersSchool = apps.get_model('app', 'UsersSchool')
    
    # Update any forms that might have inconsistent user/school relationships
    for form in Form.objects.all():
        if form.user:
            # Check if the user exists and update school_id to match user.id
            try:
                user_exists = UsersSchool.objects.filter(id=form.user.id).exists()
                if user_exists and form.school_id != form.user.id:
                    form.school_id = form.user.id
                    form.save()
            except Exception as e:
                # Skip problematic forms
                print(f"Skipping form {form.id}: {e}")
                continue


def reverse_form_user_consistency(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_assign_forms_to_users'),
    ]

    operations = [
        migrations.RunPython(ensure_form_user_consistency, reverse_form_user_consistency),
    ]
