# Generated by Django 5.2.6 on 2025-09-30 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_admin_user_system'),
    ]

    operations = [
    ]
