# Generated by Django 5.2.4 on 2025-09-17 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_admin_user_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='twofactorauth',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='twofactorauth',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='accountlockout',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='adminuserpermission',
            name='unique_admin_permission',
        ),
        migrations.RenameIndex(
            model_name='adminuser',
            new_name='admin_user_admin_l_60f17d_idx',
            old_name='admin_user_level_status_idx',
        ),
        migrations.RenameIndex(
            model_name='adminuser',
            new_name='admin_user_region__cf202c_idx',
            old_name='admin_user_coverage_idx',
        ),
        migrations.RenameIndex(
            model_name='formapproval',
            new_name='form_approv_form_id_77030d_idx',
            old_name='appr_form_level_idx',
        ),
        migrations.RenameIndex(
            model_name='formdeadline',
            new_name='form_deadli_region__1311d1_idx',
            old_name='deadline_reg_date_idx',
        ),
        migrations.RemoveField(
            model_name='accountlockout',
            name='locked_by',
        ),
        migrations.RemoveField(
            model_name='accountlockout',
            name='unlock_token',
        ),
        migrations.RemoveField(
            model_name='dataretentionpolicy',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='dataretentionpolicy',
            name='legal_basis',
        ),
        migrations.AddField(
            model_name='accountlockout',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataretentionpolicy',
            name='data_types',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dataretentionpolicy',
            name='name',
            field=models.CharField(default='Default Policy', max_length=100),
        ),
        migrations.AddField(
            model_name='form',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subquestion',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('percentage', 'Percentage')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='accountlockout',
            name='reason',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accountlockout',
            name='unlock_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountlockout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersschool'),
        ),
        migrations.AlterField(
            model_name='dataretentionpolicy',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataretentionpolicy',
            name='retention_period_days',
            field=models.IntegerField(default=365),
        ),
        migrations.AlterUniqueTogether(
            name='adminuserpermission',
            unique_together={('admin_user', 'permission_name', 'resource_type', 'action')},
        ),
        migrations.AlterUniqueTogether(
            name='form',
            unique_together={('user', 'school')},
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['action', 'timestamp'], name='adm_log_act_time_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['resource_type', 'timestamp'], name='adm_log_res_time_idx'),
        ),
        migrations.AddIndex(
            model_name='adminsession',
            index=models.Index(fields=['expires_at'], name='adm_sess_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuserpermission',
            index=models.Index(fields=['resource_type', 'action'], name='adm_perm_res_act_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['user'], name='form_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='formapproval',
            index=models.Index(fields=['approver', 'status'], name='form_approv_approve_f20ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='formapproval',
            index=models.Index(fields=['approval_level', 'status'], name='form_approv_approva_472ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='formdeadline',
            index=models.Index(fields=['division', 'deadline_date'], name='form_deadli_divisio_37374e_idx'),
        ),
        migrations.AddIndex(
            model_name='formdeadline',
            index=models.Index(fields=['district', 'deadline_date'], name='form_deadli_distric_cb1f36_idx'),
        ),
        migrations.AddIndex(
            model_name='formdeadline',
            index=models.Index(fields=['form_type', 'deadline_date'], name='form_deadli_form_ty_3d553a_idx'),
        ),
        migrations.AddIndex(
            model_name='usercreationrequest',
            index=models.Index(fields=['requested_by', 'status'], name='user_creati_request_540cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='usercreationrequest',
            index=models.Index(fields=['status', 'created_at'], name='user_creati_status_93874d_idx'),
        ),
        migrations.AddIndex(
            model_name='usersschool',
            index=models.Index(fields=['approved_by'], name='usr_sch_approved_by_idx'),
        ),
        migrations.AddIndex(
            model_name='usersschool',
            index=models.Index(fields=['approval_status'], name='usr_sch_approval_idx'),
        ),
        migrations.DeleteModel(
            name='TwoFactorAuth',
        ),
    ]
