# Generated by Django 5.2.4 on 2025-09-24 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_twofactorauth_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='district',
            field=models.ForeignKey(blank=True, db_column='district_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.district'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='division',
            field=models.ForeignKey(blank=True, db_column='division_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.division'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='region',
            field=models.ForeignKey(blank=True, db_column='region_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.region'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='school',
            field=models.ForeignKey(blank=True, db_column='school_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.school'),
        ),
        migrations.AlterField(
            model_name='form',
            name='school',
            field=models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
    ]
