# Generated by Django 4.2.24 on 2025-09-24 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_alter_adminuser_district_alter_adminuser_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormNotification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('form_submitted', 'Form Submitted'), ('form_approved', 'Form Approved'), ('form_returned', 'Form Returned'), ('form_rejected', 'Form Rejected'), ('deadline_reminder', 'Deadline Reminder'), ('overdue_notification', 'Overdue Notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_required', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'form_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='form',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='form',
            name='academic_year',
            field=models.CharField(default='2024-2025', max_length=10),
        ),
        migrations.AddField(
            model_name='form',
            name='current_level',
            field=models.CharField(choices=[('school', 'School'), ('district', 'District'), ('division', 'Division'), ('region', 'Region'), ('central', 'Central Office')], default='school', max_length=10),
        ),
        migrations.AddField(
            model_name='form',
            name='form_type',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='form',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='last_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_forms', to='app.adminuser'),
        ),
        migrations.AddField(
            model_name='form',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('district_pending', 'Pending District Review'), ('district_approved', 'District Approved'), ('district_returned', 'Returned to School'), ('division_pending', 'Pending Division Review'), ('division_approved', 'Division Approved'), ('division_returned', 'Returned to District'), ('region_pending', 'Pending Region Review'), ('region_approved', 'Region Approved'), ('region_returned', 'Returned to Division'), ('central_pending', 'Pending Central Review'), ('central_approved', 'Central Approved'), ('central_returned', 'Returned to Region'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='form',
            unique_together={('user', 'school', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['status'], name='form_status_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['current_level'], name='form_current_level_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['submitted_at'], name='form_submitted_at_idx'),
        ),
        migrations.AddField(
            model_name='formnotification',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.form'),
        ),
        migrations.AddField(
            model_name='formnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='app.adminuser'),
        ),
        migrations.AddField(
            model_name='formnotification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='app.adminuser'),
        ),
        migrations.AddIndex(
            model_name='formnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='form_notifi_recipie_d44846_idx'),
        ),
        migrations.AddIndex(
            model_name='formnotification',
            index=models.Index(fields=['form', 'notification_type'], name='form_notifi_form_id_fd0a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='formnotification',
            index=models.Index(fields=['created_at'], name='form_notifi_created_9032bf_idx'),
        ),
        migrations.AddIndex(
            model_name='formnotification',
            index=models.Index(fields=['priority', 'created_at'], name='form_notifi_priorit_092a56_idx'),
        ),
    ]
