# Generated by Django 4.2.24 on 2025-11-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_choice_answer_type'),  # Depends on core models
    ]

    operations = [
        # Add indexes to answers table for faster lookups
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_answers_form_question 
            ON answers(form_id, question_id);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_answers_form_question ON answers;"
        ),
        
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_answers_form_id 
            ON answers(form_id);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_answers_form_id ON answers;"
        ),
        
        # Add indexes to questions table for faster topic lookups
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_questions_topic_id 
            ON questions(topic_id);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_questions_topic_id ON questions;"
        ),
        
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_questions_topic_order 
            ON questions(topic_id, display_order);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_questions_topic_order ON questions;"
        ),
        
        # Add indexes to topics table for faster category lookups
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_topics_category_id 
            ON topics(category_id);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_topics_category_id ON topics;"
        ),
        
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_topics_category_order 
            ON topics(category_id, display_order);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_topics_category_order ON topics;"
        ),
        
        # Add indexes to forms table for faster user lookups
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_forms_user_school 
            ON forms(user_id, school_id);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_forms_user_school ON forms;"
        ),
        
        # Add index for required questions (commonly filtered)
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_questions_required 
            ON questions(topic_id, is_required);
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_questions_required ON questions;"
        ),
    ]
